version: '2'
services:
    invoicemanager-app:
        image: invoicemanager
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://invoicemanager-postgresql:5432/invoicemanager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8888:8888
    invoicemanager-postgresql:
        extends:
            file: postgresql.yml
            service: invoicemanager-postgresql
