version: '2'
services:
    invoicemanager-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/invoicemanager/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=invoicemanager
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
